[build]
  command = "pnpm run build"
  publish = "build/client"

[functions]
  directory = "build/server"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200



  [functions]
  node_bundler = "esbuild"
  directory = "build/server"

[functions.main]
  node_version = "20"