[build]
  command = "pnpm run build"
  publish = "build/client"

[functions]
  node_bundler = "esbuild"
  # Puntiamo direttamente al server generato da Remix
  directory = "build/server"

[functions.index]
  node_version = "20"
  node_options = "--input-type=module"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200