[build]
  command = "pnpm run build"
  publish = "build/client"

[functions]
  node_bundler = "esbuild"
  directory = "build/server"

[functions.main]
  node_version = "20"
  # Questa riga dice a Netlify di usare il formato moderno
  node_options = "--input-type=module"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200