[build]
  command = "pnpm run build"
  publish = "build/client"

[functions]
  node_bundler = "esbuild"
  directory = "build/server" # Rimosso l'asterisco finale che confonde il sistema

[functions.index] # Cambiato da .main a .index per combaciare con la riga 16
  node_version = "20"
  node_options = "--input-type=module"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200