[build]
  command = "pnpm run build"
  publish = "build/client"

[functions]
  directory = "build/server"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200