[build]
  command = "pnpm run build"
  publish = "build/client"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/remix-server"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["build/server/**"]